version: '3'
services:
  padds:
    image: "micmorris.padds.example/scala-padds-stack:latest"
    environment:
     - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
     - SERVICE_HOST=0.0.0.0
     - SERVICE_PORT=8080
    ports:
     - "8080:8080"
